name: Build, Test, and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_and_unit_test:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm run test:unit
      - name: SoftUni username avis23
        run: echo "avis23"

  ui_test:

    runs-on: ubuntu-latest
    needs: build_and_unit_test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - name: Install Dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Start the Application
        run: npm start &
      - name: Run UI Tests
        run: npm run test:ui
